##Assignment: Bridging the Gap Between Human Language and Databases

## Retrieve data

In [102]:
! curl "https://api.mockaroo.com/api/dde01370?count=1000&key=11149690" > "customers.csv"

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 99643    0 99643    0     0  58080      0 --:--:--  0:00:01 --:--:-- 58067

In [103]:
! curl "https://api.mockaroo.com/api/8ba6f630?count=1000&key=11149690" > "products.csv"

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  685k    0  685k    0     0   290k      0 --:--:--  0:00:02 --:--:--  290k

In [104]:
! curl "https://api.mockaroo.com/api/9bb4af90?count=200&key=12883420" > "Employees_Data.csv"
! curl "https://api.mockaroo.com/api/8edb9c10?count=1000&key=12883420" > "Orders_Data.csv"

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18982    0 18982    0     0  22105      0 --:--:-- --:--:-- --:--:-- 22097
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 70329    0 70329    0     0  45796      0 --:--:--  0:00:01 --:--:-- 45787

In [105]:
!ls -l *.csv

-rw-r--r-- 1 root root  99643 Sep 28 21:05 customers.csv
-rw-r--r-- 1 root root  18982 Sep 28 21:05 Employees_Data.csv
-rw-r--r-- 1 root root  70329 Sep 28 21:05 Orders_Data.csv
-rw-r--r-- 1 root root 702414 Sep 28 21:05 products.csv

## Setup database

In [106]:
import sqlite3
import pandas as pd
import os

In [107]:
import sqlite3
import pandas as pd
import os

customers_schema = """
CREATE TABLE IF NOT EXISTS customers (
    customer_id INT PRIMARY KEY, first_name VARCHAR(50), last_name VARCHAR(50),
    email VARCHAR(50), phone_number VARCHAR(50), address VARCHAR(50),
    city VARCHAR(50), country VARCHAR(50), postal_code VARCHAR(50), loyalty_points INT
);
"""

products_schema = """
CREATE TABLE IF NOT EXISTS products (
    product_id INT PRIMARY KEY, product_name TEXT, description TEXT, price DECIMAL(10,2),
    discount_percentage DECIMAL(5,2), category VARCHAR(50), brand TEXT, stock_quantity INT,
    color VARCHAR(50), size VARCHAR(20), weight DECIMAL(5,2), dimensions TEXT,
    release_date DATE, rating DECIMAL(3,1), reviews_count INT, seller_name TEXT,
    seller_rating DECIMAL(3,1), seller_reviews_count INT, shipping_method VARCHAR(20),
    shipping_cost DECIMAL(6,2)
);
"""

orders_schema = """
CREATE TABLE IF NOT EXISTS orders (
    order_id INT PRIMARY KEY, customer_id INT, product_id INT, quantity INT,
    unit_price DECIMAL(10,2), total_price DECIMAL(10,2), order_date DATE,
    shipping_address VARCHAR(255), payment_method VARCHAR(20), status VARCHAR(20),
    employee_id INT,
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
    FOREIGN KEY (product_id) REFERENCES products(product_id),
    FOREIGN KEY (employee_id) REFERENCES employees(employee_id)
);
"""

employees_schema = """
CREATE TABLE IF NOT EXISTS employees (
    employee_id INT PRIMARY KEY,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    email VARCHAR(50),
    job_title VARCHAR(50),
    department VARCHAR(50),
    hire_date DATE,
    salary INT,
    manager_id INT
);
"""


COLUMN_DATA_TYPES = {
    'customers': { 'customer_id': 'int64', 'loyalty_points': 'int64' },
    'products': { 'product_id': 'int64', 'price': 'float64', 'discount_percentage': 'float64', 'stock_quantity': 'int64', 'weight': 'float64', 'release_date': 'datetime64[ns]', 'rating': 'float64', 'reviews_count': 'int64', 'seller_rating': 'float64', 'seller_reviews_count': 'int64', 'shipping_cost': 'float64' },
    'orders': { 'order_id': 'int64', 'customer_id': 'int64', 'product_id': 'int64', 'quantity': 'int64', 'unit_price': 'float64', 'total_price': 'float64', 'order_date': 'datetime64[ns]', 'employee_id': 'int64' },
    'employees': { 'employee_id': 'int64', 'hire_date': 'datetime64[ns]', 'salary': 'int64', 'manager_id': 'Int64' } # Use Int64 for nullable integers
}

In [108]:
db_name = 'ecommerce_with_employees.db'
if os.path.exists(db_name):
    os.remove(db_name)
    print(f"Removed existing database '{db_name}'.")

conn = None
try:
    conn = sqlite3.connect(db_name)
    cursor = conn.cursor()
    print(f"New database '{db_name}' created.")

    # Create all tables
    cursor.execute(customers_schema)
    cursor.execute(products_schema)
    cursor.execute(employees_schema)  # Employees first, since orders reference it
    cursor.execute(orders_schema)
    print("All tables created successfully.")

    # CSV file → (table, schema mapping)
    csv_to_table_map = {
        'customers.csv': ('customers', COLUMN_DATA_TYPES['customers']),
        'products.csv': ('products', COLUMN_DATA_TYPES['products']),
        'Orders_Data.csv': ('orders', COLUMN_DATA_TYPES['orders']),
        'Employees_Data.csv': ('employees', COLUMN_DATA_TYPES['employees'])
    }

    for csv_file, (table_name, dtypes) in csv_to_table_map.items():
        if os.path.exists(csv_file):
            df = pd.read_csv(csv_file)

            # Enforce schema types
            for col, dtype in dtypes.items():
                if 'datetime' in dtype:
                    df[col] = pd.to_datetime(df[col], errors='coerce')
                else:
                    df[col] = pd.to_numeric(df[col], errors='coerce').astype(dtype)

            df.to_sql(table_name, conn, if_exists='append', index=False)
            print(f"Loaded data from '{csv_file}' into '{table_name}'.")
        else:
            print(f"⚠️  File '{csv_file}' not found, skipping.")

    conn.commit()
    print("\nAll data saved successfully.")

except Exception as e:
    print(f"Error: {e}")
finally:
    if conn:
        conn.close()
        print("Database connection closed.")

Removed existing database 'ecommerce_with_employees.db'.
New database 'ecommerce_with_employees.db' created.
All tables created successfully.
Loaded data from 'customers.csv' into 'customers'.
Loaded data from 'products.csv' into 'products'.
Loaded data from 'Orders_Data.csv' into 'orders'.
Loaded data from 'Employees_Data.csv' into 'employees'.

All data saved successfully.
Database connection closed.

##Prompt

In [110]:
updated_prompt = """
### **ROLE**

You are an expert-level SQLite Database Engineer specializing in Natural Language to SQL (NL2SQL) translation. Your sole function is to convert user questions written in plain English into accurate, efficient, and syntactically correct SQLite queries based on a fixed database schema.

-----

### **CONTEXT**

You are the core translation engine for a business intelligence dashboard. The database dialect is always **SQLite**.

The database consists of the following four tables:

**customers table:**
```sql
CREATE TABLE customers (
    customer_id INT PRIMARY KEY, first_name VARCHAR(50), last_name VARCHAR(50),
    email VARCHAR(50), phone_number VARCHAR(50), address VARCHAR(50),
    city VARCHAR(50), country VARCHAR(50), postal_code VARCHAR(50), loyalty_points INT
);
```

** products table:**
```sql
CREATE TABLE products (
    product_id INT PRIMARY KEY, product_name TEXT, description TEXT, price DECIMAL(10,2),
    discount_percentage DECIMAL(5,2), category VARCHAR(50), brand TEXT, stock_quantity INT,
    color VARCHAR(50), size VARCHAR(20), weight DECIMAL(5,2), dimensions TEXT,
    release_date DATE, rating DECIMAL(3,1), reviews_count INT, seller_name TEXT,
    seller_rating DECIMAL(3,1), seller_reviews_count INT, shipping_method VARCHAR(20),
    shipping_cost DECIMAL(6,2)
);
```

**orders table:**
```sql
CREATE TABLE orders (
    order_id INT PRIMARY KEY, customer_id INT, product_id INT, quantity INT,
    unit_price DECIMAL(10,2), total_price DECIMAL(10,2), order_date DATE,
    shipping_address VARCHAR(255), payment_method VARCHAR(20), status VARCHAR(20),
    employee_id INT,
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
    FOREIGN KEY (product_id) REFERENCES products(product_id),
    FOREIGN KEY (employee_id) REFERENCES employees(employee_id)
);
```

**employees table:**
```sql
CREATE TABLE employees (
    employee_id INT PRIMARY KEY, first_name VARCHAR(50), last_name VARCHAR(50),
    email VARCHAR(50), job_title VARCHAR(50), department VARCHAR(50),
    hire_date DATE, salary INT, manager_id INT
);
```

-----

### **TASK**

Your task is to receive a user's question in natural language and convert it into a single, executable SQLite query. Follow these steps meticulously:

1.  **Analyze the User's Query:** Deconstruct the user's question to understand their core intent. Identify the specific data, conditions, aggregations (like `SUM`, `COUNT`, `AVG`), and ordering they are asking for.
2.  **Map to the Schema:** Map the entities from the user's query to the appropriate tables (`customers`, `products`, `orders`) and columns. Determine the necessary `JOIN` operations using `customers.customer_id` and `products.product_id` as foreign keys in the `orders` table.
3.  **Construct the SQLite Query:** Write a clean and efficient `SELECT` statement that is syntactically correct for SQLite. Ensure all table and column names are accurate.
4.  **Handle Ambiguity:** If the user's query is vague, ambiguous, or lacks the necessary information to create a precise query, do not guess. Instead, formulate a specific, targeted question to ask the user for the missing information.

-----

### **EXAMPLES**

**Example 1:**

  * **User Query:** "What are the names of the top 3 products with the highest total revenue?"
  * **Expected Output:**
    ```json
    {
      "status": "success",
      "response": "SELECT T2.product_name FROM orders AS T1 INNER JOIN products AS T2 ON T1.product_id = T2.product_id GROUP BY T2.product_name ORDER BY SUM(T1.total_price) DESC LIMIT 3;"
    }
    ```

**Example 2: **

  * **User Query:** "Who is the highest paid employee?"
  * **Expected Output:**
    ```json
    {
      "status": "success",
      "response": "SELECT first_name, last_name, salary FROM employees ORDER BY salary DESC LIMIT 1;"
    }
    ```

-----

### **OUTPUT FORMAT**

Your final response must be a single JSON object with two keys:

1.  `"status"`: A string with one of three possible values: `"success"`, `"clarification_needed"`, or `"error"`.
2.  `"response": A string containing the SQL query, clarifying question, or error message.

"""

##Query Prompt

In [111]:
def get_sql_query(genai_client, prompt, user_query):
  contents = f"""
  {prompt}

  Here's the user query in english you need to work on:
  {user_query}
  """
  response = genai_client.models.generate_content(model="models/gemini-2.5-flash", contents=contents)

  clean_response = response.text.replace('```json', '').replace('```', '').strip()
  try:
    output = json.loads(clean_response)
  except json.JSONDecodeError:
    print(f"ERROR: The AI returned a non-JSON response: \n{clean_response}\n---")
    output = {"status": "error", "response": "The AI model did not return a valid JSON format."}
  return output

def execute_query(query, db_name='ecommerce_with_employees.db'):

    conn = None
    try:
        conn = sqlite3.connect(db_name)
        print(f"\nExecuting query on '{db_name}':\n{query}")
        results_df = pd.read_sql_query(query, conn)
        print("Query executed successfully.")
        return results_df
    except Exception as e:
        print(f"Error executing query: {e}")
        return None
    finally:
        if conn:
            conn.close()

def text2sql(genai_client, prompt, user_query):

  print(f"Translating your question: '{user_query}'")
  output = get_sql_query(genai_client, prompt, user_query)
  if output['status'] == 'success':
    results = execute_query(output['response'])
    return results
  else:
    print(f"\nReceived a non-success status: {output['status']}")
    print(f"Response: {output['response']}")
    return None

##Testing

In [112]:
print("Running your Text-to-SQL query")
user_question = "Who are the top 5 highest-paid employees?"
result = text2sql(genai_client, updated_prompt, user_question)

result

Running your Text-to-SQL query
Translating your question: 'Who are the top 5 highest-paid employees?'

Executing query on 'ecommerce_with_employees.db':
SELECT first_name, last_name, salary FROM employees ORDER BY salary DESC LIMIT 5;
Query executed successfully.

  first_name last_name  salary
0     Eloise  Houlston  995698
1     Goldie   Corradi  995336
2       Moll     Berni  993618
3     Hallsy  Duffield  974010
4  Annemarie   Quartly  962553

In [113]:
print("Running your Text-to-SQL query")
user_question = "What are the names of the top 3 products with the highest total revenue?"
result = text2sql(genai_client, updated_prompt, user_question)

result

Running your Text-to-SQL query
Translating your question: 'What are the names of the top 3 products with the highest total revenue?'

Executing query on 'ecommerce_with_employees.db':
SELECT T2.product_name FROM orders AS T1 INNER JOIN products AS T2 ON T1.product_id = T2.product_id GROUP BY T2.product_name ORDER BY SUM(T1.total_price) DESC LIMIT 3;
Query executed successfully.

                                        product_name
0  augue aliquam erat volutpat in congue etiam ju...
1  scelerisque quam turpis adipiscing lorem vitae...
2  dui proin leo odio porttitor id consequat in c...

In [114]:
print("Running your Text-to-SQL query")
user_question = "Which employee is responsible for the highest value of sales? Show their name and the total sales amount."
result = text2sql(genai_client, updated_prompt, user_question)

result

Running your Text-to-SQL query
Translating your question: 'Which employee is responsible for the highest value of sales? Show their name and the total sales amount.'

Executing query on 'ecommerce_with_employees.db':
SELECT T2.first_name, T2.last_name, SUM(T1.total_price) AS total_sales FROM orders AS T1 INNER JOIN employees AS T2 ON T1.employee_id = T2.employee_id GROUP BY T2.employee_id, T2.first_name, T2.last_name ORDER BY total_sales DESC LIMIT 1;
Query executed successfully.

  first_name last_name  total_sales
0      Dixie   Maxsted     11029.93

In [115]:
print("Running your Text-to-SQL query")
user_question = "Show me the total number of orders handled by each department."
result = text2sql(genai_client, updated_prompt, user_question)

result

Running your Text-to-SQL query
Translating your question: 'Show me the total number of orders handled by each department.'

Executing query on 'ecommerce_with_employees.db':
SELECT T2.department, COUNT(T1.order_id) AS total_orders FROM orders AS T1 INNER JOIN employees AS T2 ON T1.employee_id = T2.employee_id GROUP BY T2.department;
Query executed successfully.

                  department  total_orders
0                 Accounting           139
1       Business Development           113
2                Engineering            77
3            Human Resources            74
4                      Legal            68
5                  Marketing            79
6         Product Management            70
7   Research and Development            83
8                      Sales            61
9                   Services            92
10                   Support            54
11                  Training            90

This project demonstrated the creation of a Text-to-SQL generator using prompt engineering, where schemas, instructions, and examples enabled accurate translation of natural language into SQLite queries. The system proved scalable and adaptable, as shown by extending the schema with a new employees table and updating the orders table, while effectively handling both simple and complex JOIN operations. The work highlights the power of well-structured prompts in guiding LLMs, making database access more accessible to non-technical users. Flexibility was another strength, since schema changes required only prompt updates rather than model retraining, and the ability to ask clarifying questions further improved usability. Key lessons included the importance of accurate data preparation, secure API key management, proper environment setup, and incremental testing. Overall, the project shows how prompt engineering can transform general LLMs into practical and scalable tools that bridge human language and databases.